; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\USER\AppData\Local\Temp\.NETFramework,Version=v4.6.AssemblyAttributes.cpp"
